.github/sync-files.yaml
.github/workflows/sync-files.yaml

ci: add sync-files.yaml 

---

.pre-commit-config.yaml
NOTICE
README.md
build_depends.repos

chore: add config files

---

.github/sync-files.yaml

ci(sync-files.yaml): remove build-depends-repos

---

autoware_adapi_version_msgs/CMakeLists.txt
autoware_adapi_version_msgs/README.md
autoware_adapi_version_msgs/package.xml
autoware_adapi_version_msgs/srv/InterfaceVersion.srv

Moved [autoware_ad_api_msgs](https://github.com/autowarefoundation/autoware.universe/tree/7e2370d8542eb5542c66780fbea8df5ea8f708e5/common/autoware_ad_api_msgs) from autoware.universe.

feat(autoware_adapi_version_msgs): add version messages

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/README.md
autoware_adapi_v1_msgs/common/msg/ResponseStatus.msg
autoware_adapi_v1_msgs/localization/msg/LocalizationInitializationState.msg
autoware_adapi_v1_msgs/localization/srv/InitializeLocalization.srv
autoware_adapi_v1_msgs/package.xml
autoware_adapi_v1_msgs/routing/msg/Route.msg
autoware_adapi_v1_msgs/routing/msg/RouteData.msg
autoware_adapi_v1_msgs/routing/msg/RoutePrimitive.msg
autoware_adapi_v1_msgs/routing/msg/RouteSegment.msg
autoware_adapi_v1_msgs/routing/msg/RouteState.msg
autoware_adapi_v1_msgs/routing/srv/ClearRoute.srv
autoware_adapi_v1_msgs/routing/srv/SetRoute.srv
autoware_adapi_v1_msgs/routing/srv/SetRoutePoints.srv

Moved [autoware_ad_api_msgs]( https://github.com/autowarefoundation/autoware.universe/tree/7e2370d8542eb5542c66780fbea8df5ea8f708e5/common/autoware_ad_api_msgs) from autoware.universe.

feat(autoware_adapi_v1_msgs): add v1 messages

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/planning/msg/SteeringFactor.msg
autoware_adapi_v1_msgs/planning/msg/SteeringFactorArray.msg

- add api message for planning
https://github.com/autowarefoundation/autoware.universe/pull/1706

feat(autoware_adapi_v1_msgs): add planning api message

---

autoware_adapi_v1_msgs/routing/srv/SetRoute.srv

Add error code to route set service.

feat(autoware_adapi_v1_msgs): add error code to route set service

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/planning/msg/VelocityFactor.msg
autoware_adapi_v1_msgs/planning/msg/VelocityFactorArray.msg

Add velocity factor message.
https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/list/api/planning/velocity_factors/

feat(autoware_adapi_v1_msgs): add velocity factor message

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/routing/msg/RouteOption.msg
autoware_adapi_v1_msgs/routing/srv/SetRoute.srv
autoware_adapi_v1_msgs/routing/srv/SetRoutePoints.srv

Add option for the goal modification (https://github.com/autowarefoundation/autoware/issues/3406).

feat(autoware_adapi_v1_msgs): add routing option for goal modification

---

autoware_adapi_v1_msgs/routing/srv/SetRoute.srv

Add two new error codes for reroute error failures.

feat(autoware_adapi_v1_msgs): add new error messages

---

autoware_adapi_v1_msgs/routing/srv/SetRoutePoints.srv

Add some new error codes for route points

feat(autoware_adapi_v1_msgs): add error code for route points

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/vehicle/msg/DoorGroup.msg
autoware_adapi_v1_msgs/vehicle/msg/DoorLayout.msg
autoware_adapi_v1_msgs/vehicle/msg/VehicleDimensions.msg
autoware_adapi_v1_msgs/vehicle/srv/GetDoorLayout.srv
autoware_adapi_v1_msgs/vehicle/srv/GetVehicleDimensions.srv

- Create msgs for vehicle information
https://github.com/autowarefoundation/autoware-documentation/pull/317

feat(autoware_adapi_v1_msgs): add vehicle info msgs

---

autoware_adapi_v1_msgs/vehicle/msg/DoorLayout.msg

Modify to intuitive field names. 
Compatibility is not an issue as this API has not been released yet.
Not applicable.
Not applicable.

feat(autoware_adapi_v1_msgs): change door field names to suit

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/vehicle/msg/DoorCommand.msg
autoware_adapi_v1_msgs/vehicle/msg/DoorStatus.msg
autoware_adapi_v1_msgs/vehicle/srv/SetDoorCommand.srv

Add dppr cpommand messages. This is for [door command API](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/list/api/vehicle/doors/command/)
Not applicable.
Not applicable.

feat(autoware_adapi_v1_msgs): add door command

---

autoware_adapi_v1_msgs/system/msg/MrmState.msg

Add MRM pull over behavior to MrmState.msg. 

feat(autoware_adapi_v1_msgs): add MRM pull over behavior for mrm state

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/system/msg/DiagGraphStatus.msg
autoware_adapi_v1_msgs/system/msg/DiagGraphStruct.msg
autoware_adapi_v1_msgs/system/msg/DiagLinkStruct.msg
autoware_adapi_v1_msgs/system/msg/DiagNodeStatus.msg
autoware_adapi_v1_msgs/system/msg/DiagNodeStruct.msg

Add diagnostics message. See the [documentation](https://github.com/autowarefoundation/autoware-documentation/pull/539) for details.
https://github.com/autowarefoundation/autoware-documentation/pull/539
None.
None.
None.
None.

feat(autoware_adapi_v1_msgs): add diagnostics

---

autoware_adapi_v1_msgs/package.xml
autoware_adapi_version_msgs/package.xml

Update version to v1.6.0. From this version, the message package version will be updated to match the specification version even if there are no message changes. Check [this comment](https://github.com/autowarefoundation/autoware-documentation/pull/602#discussion_r1810108854) for background.
Not applicable.
Not applicable.
- https://github.com/autowarefoundation/autoware_adapi_msgs/pull/61
[pull …

feat: update v1.6.0

---

autoware_adapi_v1_msgs/CHANGELOG.rst
autoware_adapi_version_msgs/CHANGELOG.rst

This PR fixes the links to the issues in the `CHANGELOG.rst` file
Not applicable.
Not applicable.

fix(autoware_adapi_msgs): fix links to issues in CHANGELOG.rst files

---

autoware_adapi_v1_msgs/CHANGELOG.rst
autoware_adapi_v1_msgs/package.xml
autoware_adapi_version_msgs/CHANGELOG.rst
autoware_adapi_version_msgs/package.xml

This is kind of the preparation for the versioning on the OSS side. Hopefully this is the right approach for the versioning.
As this is the version update, I did not performed any tests. But checked if there is no any missing fixes by using following command.
```
grep -R '1.6.0' ./
grep -R 'version' ./
```
None for now
None.

feat(package.xml): versioning from `1.6.0` to `1.7.0`

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/vehicle/msg/VehicleMetrics.msg

Add metrics message. See https://github.com/autowarefoundation/autoware-documentation/pull/651 for details.
None
None.
None.

feat(autoware_adapi_v1_msgs): add metrics message

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/vehicle/msg/VehicleSpecs.msg
autoware_adapi_v1_msgs/vehicle/srv/GetVehicleSpecs.srv

Add vehicle specs message. See https://github.com/autowarefoundation/autoware-documentation/pull/650 for details.
None
None.
None.

feat(autoware_adapi_v1_msgs): add vehicle spec message

---

autoware_adapi_v1_msgs/CMakeLists.txt
autoware_adapi_v1_msgs/system/msg/MrmRequest.msg
autoware_adapi_v1_msgs/system/msg/MrmRequestList.msg
autoware_adapi_v1_msgs/system/srv/SendMrmRequest.srv

Add MRM request messages. See https://github.com/autowarefoundation/autoware-documentation/pull/649 for details.
None.
None
None.

feat(autoware_adapi_v1_msgs): add mrm request messages

---

autoware_adapi_v1_msgs/system/srv/ListMrmDescription.srv

The descriptions field should be response.
None
None.
None.

fix(autoware_adapi_v1_msgs): fix description response
